### ISSUE TITLE
inim doesn't catch out of bound error

### ISSUE THREAD

**Issue by timotheecour** [AndreiRegiani/INim#32] opened 2018-07-18 01:39 UTC
```
inim
INim 0.2.5
Nim Compiler Version 0.18.1 [MacOSX: amd64] at /Users/timothee/.nimble/bin/nim
>>> import sequtils, os
>>> echo toSeq(parentDirs("/a/b"))
@["/a/b", "/a", ""]
>>> let a=toSeq(parentDirs("/a/b"))
>>> a
@["/a/b", "/a", ""] : seq[string]
>>> a[0]
/a/b : string
>>> a[1]
/a : string
>>> a[-1]
@["/a/b", "/a", ""]
>>>

```
the last entry is shown in red  (as is the case for errors), but should show the error instead of returning non-sensical `@["/a/b", "/a", ""]`

**Comment by AndreiRegiani** [comment] 2018-07-25 23:40
Fixed on `v0.3.1`, please update `nimble install inim`

Problem was INim didn't handle runtime errors / exceptions caused by the user, now it does.

Pasting the same code above gives:

```
# ...
>>> a[-1]
Error: unhandled exception: index out of bounds [IndexError]
```

**Closed by AndreiRegiani** 2018-07-25 23:40 UTC
